### PR TITLE
Remove minSdkVersion from the library gradle

### PR DESCRIPTION
**Pull request by anasanasanas**
changes:
- Remove minSdkVersion from the library gradle

### CODE REVIEW

**Comment by Karn** [comment]
Issue: #29

**Comment by Karn** [comment]
A quick note -- we cannot simply remove the `minSdkVersion` attribute since the [lack of this attribute indicates a `minSdkVersion` of `1`](https://stackoverflow.com/a/12017802/5037824).

You need to instead update the `config.build.minSdk` value in the `gradle/configuration.gradle` file.

Edit: Looks like the build is failing for that very reason.

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':library:processDebugUnitTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 1 cannot be smaller than version 14 declared in library [androidx.core:core:1.0.1] /home/travis/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/6c44bc420de6189c80bc5bf00fec1b4a/AndroidManifest.xml as the library might be using APIs not available in 1
  	Suggestion: use a compatible library with a minSdk of at most 1,
  		or increase this project's minSdk version to at least 14,
```

**Comment by anasanasanas** [comment]
I was thinking about delegate it to the consumer of the library.
but it much safer to add it in the library with value 1.
I will update the pull request.

**Comment by anasanasanas** [comment]
Pull request #31

**Pull request closed without merging**
